before:
  hooks:
    - go mod download
builds:
  - binary: metastack
    goos:
      - darwin
      - linux
    goarch:
      - amd64
changelog:
  filters:
    exclude:
      - Merge pull request
      - Merge branch
archive:
  format: binary
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: toVersus
    name: metastack
