language: go
go: "1.13.x"

git:
  depth: 1

branches:
  only:
  - master
  - /^v.*/

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
